# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.252
loader_version_range=[1,)

## Mod Properties
mod_id=vw50
mod_name=VW50
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.example.vw50
